import 'dart:convert';

/// PersonaPath — Itinerary Model
///
/// Represents a travel itinerary generated by AI. No longer depends
/// on cloud_firestore — dates are parsed from ISO strings.

class Itinerary {
  final String id;
  final int userlocalId;
  final String title;
  final String description;
  final List<String> days;
  final List<ActivityItem> activities;
  final DateTime generatedAt;
  final Map<String, dynamic> quizAnswers;

  Itinerary({
    required this.id,
    required this.userlocalId,
    required this.title,
    required this.description,
    required this.days,
    required this.activities,
    required this.generatedAt,
    required this.quizAnswers,
  });

  /// Parse from server JSON response (itinerary endpoint)
  factory Itinerary.fromJson(Map<String, dynamic> json) {
    final generated = json['created_at'] ?? json['generatedAt'];
    DateTime parsed;
    if (generated is String) {
      parsed = DateTime.tryParse(generated) ?? DateTime.now();
    } else {
      parsed = DateTime.now();
    }

    // Parse itinerary_content if it's a JSON string
    Map<String, dynamic> content = {};
    final rawContent = json['itinerary_content'];
    if (rawContent is String && rawContent.isNotEmpty) {
      try {
        content = Map<String, dynamic>.from(
          _tryParseJson(rawContent) ?? {},
        );
      } catch (_) {}
    }

    final quizAnswers = <String, dynamic>{};
    if (json['quizAnswers'] is Map) {
      quizAnswers.addAll(Map<String, dynamic>.from(json['quizAnswers'] as Map));
    }

    return Itinerary(
      id: (json['tid'] ?? json['id'] ?? '').toString(),
      userlocalId: json['uid'] ?? json['userlocalId'] ?? 0,
      title: json['title'] ?? content['title'] ?? json['name'] ?? '',
      description: json['description'] ?? content['description'] ?? '',
      days: List<String>.from(content['days'] ?? json['days'] ?? const []),
      activities: (content['activities'] as List<dynamic>? ??
              json['activities'] as List<dynamic>? ??
              const [])
          .map((e) => ActivityItem.fromMap(e as Map<String, dynamic>))
          .toList(),
      generatedAt: parsed,
      quizAnswers: quizAnswers,
    );
  }

  /// Legacy factory for backward compat
  factory Itinerary.fromMap(String id, Map<String, dynamic> map) {
    return Itinerary.fromJson({...map, 'id': id});
  }

  Map<String, dynamic> toMap() {
    return {
      'userlocalId': userlocalId,
      'title': title,
      'description': description,
      'days': days,
      'activities': activities.map((e) => e.toMap()).toList(),
      'generatedAt': generatedAt.toIso8601String(),
      'quizAnswers': quizAnswers,
    };
  }

  /// Convert to JSON string for server storage
  String toContentJson() {
    return '{${[
      '"title": "${_escape(title)}"',
      '"description": "${_escape(description)}"',
      '"days": [${days.map((d) => '"${_escape(d)}"').join(', ')}]',
      '"activities": [${activities.map((a) => '{"day":"${_escape(a.day)}","time":"${_escape(a.time)}","title":"${_escape(a.title)}","note":"${_escape(a.note)}"}').join(', ')}]',
    ].join(', ')}}';
  }

  static String _escape(String s) => s.replaceAll('"', '\\"');

  static Map<String, dynamic>? _tryParseJson(String text) {
    try {
      // ignore: avoid_dynamic_calls
      return Map<String, dynamic>.from(
        (const JsonDecoder().convert(text)) as Map,
      );
    } catch (_) {
      return null;
    }
  }
}

class ActivityItem {
  final String day;
  final String time;
  final String title;
  final String note;

  const ActivityItem({
    required this.day,
    required this.time,
    required this.title,
    required this.note,
  });

  factory ActivityItem.fromMap(Map<String, dynamic> map) {
    return ActivityItem(
      day: map['day'] ?? '',
      time: map['time'] ?? '',
      title: map['title'] ?? '',
      note: map['note'] ?? '',
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'day': day,
      'time': time,
      'title': title,
      'note': note,
    };
  }
}

extension ItineraryCopyWith on Itinerary {
  Itinerary copyWithId(String id) {
    return Itinerary(
      id: id,
      userlocalId: userlocalId,
      title: title,
      description: description,
      days: days,
      activities: activities,
      generatedAt: generatedAt,
      quizAnswers: quizAnswers,
    );
  }
}
