// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOU3q6si8enNDlDblrv8bMtgsakVKgri4',
    appId: '1:1095582570401:android:c2cca8db336d3671079de0',
    messagingSenderId: '1095582570401',
    projectId: 'peronapath',
    storageBucket: 'peronapath.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7CFpLAsqejYI58M-AwOiUgSPNbBHupzQ',
    appId: '1:1095582570401:web:dc29a57af9cb7309079de0',
    messagingSenderId: '1095582570401',
    projectId: 'peronapath',
    authDomain: 'peronapath.firebaseapp.com',
    storageBucket: 'peronapath.firebasestorage.app',
    measurementId: 'G-5PXXZV2T9R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4TBDkRMN3KruegKak3NUGfIpVt4evRBU',
    appId: '1:1095582570401:ios:3ece4ee19df5b3f3079de0',
    messagingSenderId: '1095582570401',
    projectId: 'peronapath',
    storageBucket: 'peronapath.firebasestorage.app',
    iosBundleId: 'com.example.personaPath',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4TBDkRMN3KruegKak3NUGfIpVt4evRBU',
    appId: '1:1095582570401:ios:3ece4ee19df5b3f3079de0',
    messagingSenderId: '1095582570401',
    projectId: 'peronapath',
    storageBucket: 'peronapath.firebasestorage.app',
    iosBundleId: 'com.example.personaPath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7CFpLAsqejYI58M-AwOiUgSPNbBHupzQ',
    appId: '1:1095582570401:web:6c02279fa8c15263079de0',
    messagingSenderId: '1095582570401',
    projectId: 'peronapath',
    authDomain: 'peronapath.firebaseapp.com',
    storageBucket: 'peronapath.firebasestorage.app',
    measurementId: 'G-2RZJ56GQFW',
  );

}